# Form implementation generated from reading ui file 'c:\Users\esteb\Desktop\Tesis VTK Microk\view\ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(707, 426)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setStyleSheet("/* Fondo general */\n"
"QMainWindow {\n"
"    background-color: #f5f5f5;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* Barra de botones principal (fila de navegación) */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #2E60A9;\n"
"    border: none;\n"
"    font-size: 12px;\n"
"    font-weight: light;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"/* Hover */\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"/* Pressed */\n"
"QPushButton:pressed {\n"
"    text-decoration: underline;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Checked */\n"
"QPushButton:checked {\n"
"    background-color: #2E60A9;\n"
"    color: #FFFFFF;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"}\n"
"\n"
"#buttonContainer {\n"
"    background-color: #2E60A9;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    min-height: 100px;\n"
"    max-height: 100px;\n"
"}\n"
"\n"
"#buttonContainer QToolButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: none;\n"
"    font-size: 14px;\n"
"    padding: 5px 12px;\n"
"}\n"
"\n"
"#buttonContainer QToolButton :hover {\n"
"    text-decoration: underline;\n"
"}\n"
"\n"
"#buttonContainer QToolButton :checked {\n"
"    background-color: white;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bnt_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bnt_home.setObjectName("bnt_home")
        self.horizontalLayout.addWidget(self.bnt_home)
        self.btn_preprocessing = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_preprocessing.setObjectName("btn_preprocessing")
        self.horizontalLayout.addWidget(self.btn_preprocessing)
        self.btn_analysis = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_analysis.setObjectName("btn_analysis")
        self.horizontalLayout.addWidget(self.btn_analysis)
        self.btn_measure = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_measure.setObjectName("btn_measure")
        self.horizontalLayout.addWidget(self.btn_measure)
        self.btn_visualization = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_visualization.setObjectName("btn_visualization")
        self.horizontalLayout.addWidget(self.btn_visualization)
        self.btn_utilities = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_utilities.setObjectName("btn_utilities")
        self.horizontalLayout.addWidget(self.btn_utilities)
        self.btn_faq = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_faq.setObjectName("btn_faq")
        self.horizontalLayout.addWidget(self.btn_faq)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.buttonContainer = QtWidgets.QWidget(parent=self.centralwidget)
        self.buttonContainer.setObjectName("buttonContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttonContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton = QtWidgets.QToolButton(parent=self.buttonContainer)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.pushButton = QtWidgets.QPushButton(parent=self.buttonContainer)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.buttonContainer)
        self.workspace = QtWidgets.QWidget(parent=self.centralwidget)
        self.workspace.setObjectName("workspace")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.workspace)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.workspace)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.workspace)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bnt_home.setText(_translate("MainWindow", "Home"))
        self.btn_preprocessing.setText(_translate("MainWindow", "Preprocessing"))
        self.btn_analysis.setText(_translate("MainWindow", "Analysis"))
        self.btn_measure.setText(_translate("MainWindow", "Measure"))
        self.btn_visualization.setText(_translate("MainWindow", "Visualization"))
        self.btn_utilities.setText(_translate("MainWindow", "Utilities"))
        self.btn_faq.setText(_translate("MainWindow", "FAQ"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
